version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: flask run --host=0.0.0.0
