name: Build and Test

on:
  label:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        sudo virtualenv env1 
        source env1/bin/activate
        pip install -r requirements.txt
  
    - name: Run application 
      run: |
        pm2 start app.py --name flask-app --interpreter=python3
